language: java
jdk:
  - oraclejdk8
env:
  - NODE_VERSION="9"
before_install:
  - nvm install $NODE_VERSION
install:
  - npm install
script:
  - unset JAVA_TOOL_OPTIONS
  - npm test
  - unset JAVA_TOOL_OPTIONS && node node_modules/react-scripts-kotlin/scripts/build.js
after_failure: "cat /home/travis/.npm/_logs/*.log"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  repo: attrib/attrib.github.io
  local_dir: build
  target_branch: master
  on:
    branch: master