language: java
jdk:
  - oraclejdk8
env:
  - NODE_VERSION="9"
before_install:
  - nvm install $NODE_VERSION
script:
  - unset _JAVA_OPTIONS
  - ./gradlew test
  - unset CI
  - ./gradlew bundle
after_failure: "cat client/build/logs/*.log"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  repo: attrib/attrib.github.io
  local_dir: build
  target_branch: master
  on:
    branch: master