language: java
jdk:
  - oraclejdk9
env:
  - NODE_VERSION="9"
before_install:
  - export PRODUCTION="true"
  - nvm install $NODE_VERSION
#install: ./gradlew assemble --debug
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  repo: attrib/attrib.github.io
  local_dir: publish
  target_branch: master
  on:
    branch: master