language: java
jdk:
  - oraclejdk8
env:
  - NODE_VERSION="9"
before_install:
  - PRODUCTION="true"
  - nvm install $NODE_VERSION
after_failure: "cat client/build/logs/*.log"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  repo: attrib/attrib.github.io
  local_dir: publish
  target_branch: master
  on:
    branch: master