FROM ubuntu

ENV DEBIAN_FRONTEND noninteractive

# Install dependencies
RUN apt-get update && \
    apt-get install -yq curl lib32gcc1 && \
    rm -rf /var/lib/apt/lists/* && \
    # Download and extract SteamCMD
    mkdir -p /opt/steamcmd && \
    cd /opt/steamcmd && \
    curl -s http://media.steampowered.com/installer/steamcmd_linux.tar.gz | tar -vxz

VOLUME /data

WORKDIR /opt/steamcmd

# This container will be executable
ENTRYPOINT ["./steamcmd.sh"]