rm client/src/main/web/Icons/*
cd client/src/main/web/Icons
wget https://beta.legiontd2.com/images/textures/Icons/Immaterial.png
wget https://beta.legiontd2.com/images/textures/Icons/Swift.png
wget https://beta.legiontd2.com/images/textures/Icons/Natural.png
wget https://beta.legiontd2.com/images/textures/Icons/Arcane.png
wget https://beta.legiontd2.com/images/textures/Icons/Fortified.png
wget https://beta.legiontd2.com/images/textures/Icons/Illegal.png
wget https://beta.legiontd2.com/images/textures/Icons/Pierce.png
wget https://beta.legiontd2.com/images/textures/Icons/Impact.png
wget https://beta.legiontd2.com/images/textures/Icons/Magic.png
wget https://beta.legiontd2.com/images/textures/Icons/Siege.png
wget https://beta.legiontd2.com/images/textures/Icons/Pure.png
wget https://beta.legiontd2.com/images/textures/Icons/None.png
wget https://beta.legiontd2.com/images/textures/Icons/Melee.png
wget https://beta.legiontd2.com/images/textures/Icons/Ranged.png
wget https://beta.legiontd2.com/images/textures/Icons/Fighter.png
wget https://beta.legiontd2.com/images/textures/Icons/Creature.png
wget https://beta.legiontd2.com/images/textures/Icons/Mercenary.png
wget https://beta.legiontd2.com/images/textures/Icons/King.png
wget https://beta.legiontd2.com/images/textures/Icons/Worker.png
wget https://beta.legiontd2.com/images/textures/Icons/AmplifyMagic.png
wget https://beta.legiontd2.com/images/textures/Icons/MoltenShield.png
wget https://beta.legiontd2.com/images/textures/Icons/Energize.png
wget https://beta.legiontd2.com/images/textures/Icons/MythiumCore.png
wget https://beta.legiontd2.com/images/textures/Icons/MarkTarget.png
wget https://beta.legiontd2.com/images/textures/Icons/Fragrance.png
wget https://beta.legiontd2.com/images/textures/Icons/NoxiousScent.png
wget https://beta.legiontd2.com/images/textures/Icons/SkeletalRegeneration.png
wget https://beta.legiontd2.com/images/textures/Icons/KillingSpree.png
wget https://beta.legiontd2.com/images/textures/Icons/Mindwarp.png
wget https://beta.legiontd2.com/images/textures/Icons/Pet.png
wget https://beta.legiontd2.com/images/textures/Icons/Cannibalism.png
wget https://beta.legiontd2.com/images/textures/Icons/SkullStew.png
wget https://beta.legiontd2.com/images/textures/Icons/Stunned.png
wget https://beta.legiontd2.com/images/textures/Icons/HealingAura.png
wget https://beta.legiontd2.com/images/textures/Icons/SafetyAura.png
wget https://beta.legiontd2.com/images/textures/Icons/LeadershipAura.png
wget https://beta.legiontd2.com/images/textures/Icons/Villainy.png
wget https://beta.legiontd2.com/images/textures/Icons/BloodRush.png
wget https://beta.legiontd2.com/images/textures/Icons/KrakenPoison.png
wget https://beta.legiontd2.com/images/textures/Icons/Build.png
wget https://beta.legiontd2.com/images/textures/Icons/NewlyDeployed.png
wget https://beta.legiontd2.com/images/textures/Icons/Delusion.png
wget https://beta.legiontd2.com/images/textures/Icons/Combustion.png
wget https://beta.legiontd2.com/images/textures/Icons/CrushingBlow.png
wget https://beta.legiontd2.com/images/textures/Icons/Fatality.png
wget https://beta.legiontd2.com/images/textures/Icons/StoneForm.png
wget https://beta.legiontd2.com/images/textures/Icons/Anaphylaxis.png
wget https://beta.legiontd2.com/images/textures/Icons/Council.png
wget https://beta.legiontd2.com/images/textures/Icons/NaturesTouch.png
wget https://beta.legiontd2.com/images/textures/Icons/Bufotoxin.png
wget https://beta.legiontd2.com/images/textures/Icons/PrismaticShield.png
wget https://beta.legiontd2.com/images/textures/Icons/BossUnit.png
wget https://beta.legiontd2.com/images/textures/Icons/Leech.png
wget https://beta.legiontd2.com/images/textures/Icons/LeakedUnit.png
wget https://beta.legiontd2.com/images/textures/Icons/Overheat.png
wget https://beta.legiontd2.com/images/textures/Icons/Haste.png
wget https://beta.legiontd2.com/images/textures/Icons/Wither.png
wget https://beta.legiontd2.com/images/textures/Icons/Maul.png
wget https://beta.legiontd2.com/images/textures/Icons/Lacerate.png
wget https://beta.legiontd2.com/images/textures/Icons/DeathStare.png
wget https://beta.legiontd2.com/images/textures/Icons/StoneSkin.png
wget https://beta.legiontd2.com/images/textures/Icons/AerialCommand.png
wget https://beta.legiontd2.com/images/textures/Icons/Indomitable.png
wget https://beta.legiontd2.com/images/textures/Icons/ReconstructiveExoskeleton.png
wget https://beta.legiontd2.com/images/textures/Icons/Paraphylaxis.png
wget https://beta.legiontd2.com/images/textures/Icons/Impale.png
wget https://beta.legiontd2.com/images/textures/Icons/Savior.png
wget https://beta.legiontd2.com/images/textures/Icons/Heroism.png
wget https://beta.legiontd2.com/images/textures/Icons/Hero.png
wget https://beta.legiontd2.com/images/textures/Icons/Villain.png
wget https://beta.legiontd2.com/images/textures/Icons/Sacrifice.png
wget https://beta.legiontd2.com/images/textures/Icons/Sorcery.png
wget https://beta.legiontd2.com/images/textures/Icons/Sorcerer.png
wget https://beta.legiontd2.com/images/textures/Icons/Ambush.png
wget https://beta.legiontd2.com/images/textures/Icons/Harden%28Active%29.png
wget https://beta.legiontd2.com/images/textures/Icons/Harden%28Recovering%29.png
wget https://beta.legiontd2.com/images/textures/Icons/Stimpack.png
wget https://beta.legiontd2.com/images/textures/Icons/Generator.png
wget https://beta.legiontd2.com/images/textures/Icons/IonicForce.png
wget https://beta.legiontd2.com/images/textures/Icons/CellRegrowth.png
wget https://beta.legiontd2.com/images/textures/Icons/Booster.png
wget https://beta.legiontd2.com/images/textures/Icons/Sprint.png
wget https://beta.legiontd2.com/images/textures/Icons/Resonance.png
wget https://beta.legiontd2.com/images/textures/Icons/ShellShock.png
wget https://beta.legiontd2.com/images/textures/Icons/Delicacy.png
wget https://beta.legiontd2.com/images/textures/Icons/DarkRitual.png
wget https://beta.legiontd2.com/images/textures/Icons/ThickHide.png
wget https://beta.legiontd2.com/images/textures/Icons/EliteFisherman.png
wget https://beta.legiontd2.com/images/textures/Icons/Vampire.png
wget https://beta.legiontd2.com/images/textures/Icons/Vampirism.png
wget https://beta.legiontd2.com/images/textures/Icons/Sorcerer%28ManaRegen%29.png
wget https://beta.legiontd2.com/images/textures/Icons/Sorcerer%28SpellDamage%29.png
wget https://beta.legiontd2.com/images/textures/Icons/Sorcery%28ManaRegen%29.png
wget https://beta.legiontd2.com/images/textures/Icons/Sorcery%28SpellDamage%29.png
wget https://beta.legiontd2.com/images/textures/Icons/Invulnerable.png
wget https://beta.legiontd2.com/images/textures/Icons/Incubation.png
wget https://beta.legiontd2.com/images/textures/Icons/PrematurelyHatched.png
wget https://beta.legiontd2.com/images/textures/Icons/Incubation%28Phase2%29.png
wget https://beta.legiontd2.com/images/textures/Icons/Incubation%28Phase3%29.png
wget https://beta.legiontd2.com/images/textures/Icons/Invigorate.png
wget https://beta.legiontd2.com/images/textures/Icons/TreasureHunt.png
wget https://beta.legiontd2.com/images/textures/Icons/InsatiableHunger.png
wget https://beta.legiontd2.com/images/textures/Icons/Acrobatics.png
wget https://beta.legiontd2.com/images/textures/Icons/Dominion.png
wget https://beta.legiontd2.com/images/textures/Icons/Entourage.png
wget https://beta.legiontd2.com/images/textures/Icons/GaiaShield.png
wget https://beta.legiontd2.com/images/textures/Icons/UpgradeKingAttack.png
wget https://beta.legiontd2.com/images/textures/Icons/UpgradeKingRegen.png
wget https://beta.legiontd2.com/images/textures/Icons/UpgradeKingSpell.png
wget https://beta.legiontd2.com/images/textures/Icons/Immolation.png
wget https://beta.legiontd2.com/images/textures/Icons/GiantSlayer.png
wget https://beta.legiontd2.com/images/textures/Icons/Fury.png
wget https://beta.legiontd2.com/images/textures/Icons/LightningHammer.png
wget https://beta.legiontd2.com/images/textures/Icons/ChainFrost.png
wget https://beta.legiontd2.com/images/textures/Icons/PunchingBag.png
wget https://beta.legiontd2.com/images/textures/Icons/Charging.png
wget https://beta.legiontd2.com/images/textures/Icons/Stampede.png
wget https://beta.legiontd2.com/images/textures/Icons/ThunderousCharge.png
wget https://beta.legiontd2.com/images/textures/Icons/AncientPower.png
wget https://beta.legiontd2.com/images/textures/Icons/Tantrum.png
wget https://beta.legiontd2.com/images/textures/Icons/SpiritOffering.png
wget https://beta.legiontd2.com/images/textures/Icons/SpiritOfferingCosmetic.png
wget https://beta.legiontd2.com/images/textures/Icons/ArmWithShuriken.png
wget https://beta.legiontd2.com/images/textures/Icons/GraniteSkin.png
wget https://beta.legiontd2.com/images/textures/Icons/Protector.png
wget https://beta.legiontd2.com/images/textures/Icons/ProtectionAura.png
wget https://beta.legiontd2.com/images/textures/Icons/GuardianAngel.png
wget https://beta.legiontd2.com/images/textures/Icons/Magician.png
wget https://beta.legiontd2.com/images/textures/Icons/MagicAura.png
wget https://beta.legiontd2.com/images/textures/Icons/ShurikenCyclone.png
wget https://beta.legiontd2.com/images/textures/Icons/ShurikenGlow.png
wget https://beta.legiontd2.com/images/textures/Icons/ShallowGrave.png
wget https://beta.legiontd2.com/images/textures/Icons/ShallowGraveGhost.png
wget https://beta.legiontd2.com/images/textures/Icons/ShallowGraveGhostRed.png
wget https://beta.legiontd2.com/images/textures/Icons/KingX2Haste.png
wget https://beta.legiontd2.com/images/textures/Icons/WintryTouch.png
wget https://beta.legiontd2.com/images/textures/Icons/FrozenVeil.png
wget https://beta.legiontd2.com/images/textures/Icons/NimbleFeet.png
wget https://beta.legiontd2.com/images/textures/Icons/Element.png
wget https://beta.legiontd2.com/images/textures/Icons/Forsaken.png
wget https://beta.legiontd2.com/images/textures/Icons/Grove.png
wget https://beta.legiontd2.com/images/textures/Icons/Mech.png
wget https://beta.legiontd2.com/images/textures/Icons/Aspect.png
wget https://beta.legiontd2.com/images/textures/Icons/Atlantean.png
wget https://beta.legiontd2.com/images/textures/Icons/Mastermind.png
wget https://beta.legiontd2.com/images/textures/Icons/Nomad.png
wget https://beta.legiontd2.com/images/textures/Icons/Shrine.png
wget https://beta.legiontd2.com/images/textures/Icons/Proton.png
wget https://beta.legiontd2.com/images/textures/Icons/Atom.png
wget https://beta.legiontd2.com/images/textures/Icons/AquaSpirit.png
wget https://beta.legiontd2.com/images/textures/Icons/RogueWave.png
wget https://beta.legiontd2.com/images/textures/Icons/Windhawk.png
wget https://beta.legiontd2.com/images/textures/Icons/Violet.png
wget https://beta.legiontd2.com/images/textures/Icons/Mudman.png
wget https://beta.legiontd2.com/images/textures/Icons/Golem.png
wget https://beta.legiontd2.com/images/textures/Icons/Disciple.png
wget https://beta.legiontd2.com/images/textures/Icons/Starcaller.png
wget https://beta.legiontd2.com/images/textures/Icons/FireElemental.png
wget https://beta.legiontd2.com/images/textures/Icons/Fenix.png
wget https://beta.legiontd2.com/images/textures/Icons/Peewee.png
wget https://beta.legiontd2.com/images/textures/Icons/Veteran.png
wget https://beta.legiontd2.com/images/textures/Icons/Bazooka.png
wget https://beta.legiontd2.com/images/textures/Icons/Pyro.png
wget https://beta.legiontd2.com/images/textures/Icons/Zeus.png
wget https://beta.legiontd2.com/images/textures/Icons/APS.png
wget https://beta.legiontd2.com/images/textures/Icons/MPS.png
wget https://beta.legiontd2.com/images/textures/Icons/Tempest.png
wget https://beta.legiontd2.com/images/textures/Icons/Leviathan.png
wget https://beta.legiontd2.com/images/textures/Icons/Berserker.png
wget https://beta.legiontd2.com/images/textures/Icons/Fatalizer.png
wget https://beta.legiontd2.com/images/textures/Icons/Millennium.png
wget https://beta.legiontd2.com/images/textures/Icons/DoomsdayMachine.png
wget https://beta.legiontd2.com/images/textures/Icons/Reactor.png
wget https://beta.legiontd2.com/images/textures/Icons/Buzz.png
wget https://beta.legiontd2.com/images/textures/Icons/Consort.png
wget https://beta.legiontd2.com/images/textures/Icons/Ranger.png
wget https://beta.legiontd2.com/images/textures/Icons/Daphne.png
wget https://beta.legiontd2.com/images/textures/Icons/Wileshroom.png
wget https://beta.legiontd2.com/images/textures/Icons/Canopie.png
wget https://beta.legiontd2.com/images/textures/Icons/Honeyflower.png
wget https://beta.legiontd2.com/images/textures/Icons/Deathcap.png
wget https://beta.legiontd2.com/images/textures/Icons/Antler.png
wget https://beta.legiontd2.com/images/textures/Icons/Whitemane.png
wget https://beta.legiontd2.com/images/textures/Icons/BananaBunk.png
wget https://beta.legiontd2.com/images/textures/Icons/BananaHaven.png
wget https://beta.legiontd2.com/images/textures/Icons/BoneWarrior.png
wget https://beta.legiontd2.com/images/textures/Icons/BoneCrusher.png
wget https://beta.legiontd2.com/images/textures/Icons/FireArcher.png
wget https://beta.legiontd2.com/images/textures/Icons/DarkMage.png
wget https://beta.legiontd2.com/images/textures/Icons/Gargoyle.png
wget https://beta.legiontd2.com/images/textures/Icons/GreenDevil.png
wget https://beta.legiontd2.com/images/textures/Icons/Gateguard.png
wget https://beta.legiontd2.com/images/textures/Icons/Harbinger.png
wget https://beta.legiontd2.com/images/textures/Icons/Butcher.png
wget https://beta.legiontd2.com/images/textures/Icons/HeadChef.png
wget https://beta.legiontd2.com/images/textures/Icons/Nightmare.png
wget https://beta.legiontd2.com/images/textures/Icons/Doppelganger.png
wget https://beta.legiontd2.com/images/textures/Icons/LordOfDeath.png
wget https://beta.legiontd2.com/images/textures/Icons/Hades.png
wget https://beta.legiontd2.com/images/textures/Icons/OldHound.png
wget https://beta.legiontd2.com/images/textures/Icons/ChaosHound.png
wget https://beta.legiontd2.com/images/textures/Icons/Diabolic.png
wget https://beta.legiontd2.com/images/textures/Icons/Imp.png
wget https://beta.legiontd2.com/images/textures/Icons/Crab.png
wget https://beta.legiontd2.com/images/textures/Icons/Hopper.png
wget https://beta.legiontd2.com/images/textures/Icons/Scorpion.png
wget https://beta.legiontd2.com/images/textures/Icons/QuillShooter.png
wget https://beta.legiontd2.com/images/textures/Icons/FlyingChicken.png
wget https://beta.legiontd2.com/images/textures/Icons/Rocko.png
wget https://beta.legiontd2.com/images/textures/Icons/Mantis.png
wget https://beta.legiontd2.com/images/textures/Icons/DireToad.png
wget https://beta.legiontd2.com/images/textures/Icons/Wale.png
wget https://beta.legiontd2.com/images/textures/Icons/Granddaddy.png
wget https://beta.legiontd2.com/images/textures/Icons/Carapace.png
wget https://beta.legiontd2.com/images/textures/Icons/Kobra.png
wget https://beta.legiontd2.com/images/textures/Icons/MetalDragon.png
wget https://beta.legiontd2.com/images/textures/Icons/WaleChief.png
wget https://beta.legiontd2.com/images/textures/Icons/KillerSlug.png
wget https://beta.legiontd2.com/images/textures/Icons/Quadrapus.png
wget https://beta.legiontd2.com/images/textures/Icons/DrillGolem.png
wget https://beta.legiontd2.com/images/textures/Icons/Sludge.png
wget https://beta.legiontd2.com/images/textures/Icons/Cardinal.png
wget https://beta.legiontd2.com/images/textures/Icons/Maccabeus.png
wget https://beta.legiontd2.com/images/textures/Icons/Snail.png
wget https://beta.legiontd2.com/images/textures/Icons/Lizard.png
wget https://beta.legiontd2.com/images/textures/Icons/Fiend.png
wget https://beta.legiontd2.com/images/textures/Icons/Brute.png
wget https://beta.legiontd2.com/images/textures/Icons/DragonTurtle.png
wget https://beta.legiontd2.com/images/textures/Icons/Hermit.png
wget https://beta.legiontd2.com/images/textures/Icons/Dino.png
wget https://beta.legiontd2.com/images/textures/Icons/SafetyMole.png
wget https://beta.legiontd2.com/images/textures/Icons/Drake.png
wget https://beta.legiontd2.com/images/textures/Icons/Mimic.png
wget https://beta.legiontd2.com/images/textures/Icons/PackLeader.png
wget https://beta.legiontd2.com/images/textures/Icons/Centaur.png
wget https://beta.legiontd2.com/images/textures/Icons/FourEyes.png
wget https://beta.legiontd2.com/images/textures/Icons/Shaman.png
wget https://beta.legiontd2.com/images/textures/Icons/GhostKnight.png
wget https://beta.legiontd2.com/images/textures/Icons/Kraken.png
wget https://beta.legiontd2.com/images/textures/Icons/Janus.png
wget https://beta.legiontd2.com/images/textures/Icons/Town.png
wget https://beta.legiontd2.com/images/textures/Icons/Barracks.png
wget https://beta.legiontd2.com/images/textures/Icons/AdvancedBarracks.png
wget https://beta.legiontd2.com/images/textures/Icons/KingUpgrader.png
wget https://beta.legiontd2.com/images/textures/Icons/LegionLord.png
wget https://beta.legiontd2.com/images/textures/Icons/MythiumDummy.png
wget https://beta.legiontd2.com/images/textures/Icons/UndeadDragon.png
wget https://beta.legiontd2.com/images/textures/Icons/WaveInProgress.png
wget https://beta.legiontd2.com/images/textures/Icons/FireLord.png
wget https://beta.legiontd2.com/images/textures/Icons/ScorpionKing.png
wget https://beta.legiontd2.com/images/textures/Icons/GiantQuadrapus.png
wget https://beta.legiontd2.com/images/textures/Icons/TestMercenary.png
wget https://beta.legiontd2.com/images/textures/Icons/TestMercenary2.png
wget https://beta.legiontd2.com/images/textures/Icons/TestBarracks.png
wget https://beta.legiontd2.com/images/textures/Icons/TestFighter.png
wget https://beta.legiontd2.com/images/textures/Icons/TestBuilder.png
wget https://beta.legiontd2.com/images/textures/Icons/TestFighterUpgrade.png
wget https://beta.legiontd2.com/images/textures/Icons/TestWorker.png
wget https://beta.legiontd2.com/images/textures/Icons/SkyKing.png
wget https://beta.legiontd2.com/images/textures/Icons/TestMercenary3.png
wget https://beta.legiontd2.com/images/textures/Icons/EarthKing.png
wget https://beta.legiontd2.com/images/textures/Icons/LegionKing.png
wget https://beta.legiontd2.com/images/textures/Icons/Cerberus.png
wget https://beta.legiontd2.com/images/textures/Icons/2xWorkers.png
wget https://beta.legiontd2.com/images/textures/Icons/GiantSnail.png
wget https://beta.legiontd2.com/images/textures/Icons/SeaSerpent.png
wget https://beta.legiontd2.com/images/textures/Icons/Deepcoiler.png
wget https://beta.legiontd2.com/images/textures/Icons/Pollywog.png
wget https://beta.legiontd2.com/images/textures/Icons/Seraphin.png
wget https://beta.legiontd2.com/images/textures/Icons/Devilfish.png
wget https://beta.legiontd2.com/images/textures/Icons/Angler.png
wget https://beta.legiontd2.com/images/textures/Icons/BountyHunter.png
wget https://beta.legiontd2.com/images/textures/Icons/Kingpin.png
wget https://beta.legiontd2.com/images/textures/Icons/Grarl.png
wget https://beta.legiontd2.com/images/textures/Icons/KingClaw.png
wget https://beta.legiontd2.com/images/textures/Icons/OceanTemplar.png
wget https://beta.legiontd2.com/images/textures/Icons/PriestessoftheAbyss.png
wget https://beta.legiontd2.com/images/textures/Icons/Azeria.png
wget https://beta.legiontd2.com/images/textures/Icons/Eggsack.png
wget https://beta.legiontd2.com/images/textures/Icons/Hydra.png
wget https://beta.legiontd2.com/images/textures/Icons/CaveFlag.png
wget https://beta.legiontd2.com/images/textures/Icons/LaneFlag.png
wget https://beta.legiontd2.com/images/textures/Icons/CorridorGate.png
wget https://beta.legiontd2.com/images/textures/Icons/MercenaryFlag.png
wget https://beta.legiontd2.com/images/textures/Icons/MercenaryAttackFlag.png
wget https://beta.legiontd2.com/images/textures/Icons/SiegeRam.png
wget https://beta.legiontd2.com/images/textures/Icons/Hydraling.png
wget https://beta.legiontd2.com/images/textures/Icons/Looter.png
wget https://beta.legiontd2.com/images/textures/Icons/PackRat.png
wget https://beta.legiontd2.com/images/textures/Icons/PackRat%28Footprints%29.png
wget https://beta.legiontd2.com/images/textures/Icons/Ogre.png
wget https://beta.legiontd2.com/images/textures/Icons/Harpy.png
wget https://beta.legiontd2.com/images/textures/Icons/SkyQueen.png
wget https://beta.legiontd2.com/images/textures/Icons/Froggo.png
wget https://beta.legiontd2.com/images/textures/Icons/Witch.png
wget https://beta.legiontd2.com/images/textures/Icons/Warg.png
wget https://beta.legiontd2.com/images/textures/Icons/Lioness.png
wget https://beta.legiontd2.com/images/textures/Icons/AlphaMale.png
wget https://beta.legiontd2.com/images/textures/Icons/DesertPilgrim.png
wget https://beta.legiontd2.com/images/textures/Icons/LostChieftain.png
wget https://beta.legiontd2.com/images/textures/Icons/SandBadger.png
wget https://beta.legiontd2.com/images/textures/Icons/IronScales.png
wget https://beta.legiontd2.com/images/textures/Icons/RedEyes.png
wget https://beta.legiontd2.com/images/textures/Icons/GreatBoar.png
wget https://beta.legiontd2.com/images/textures/Icons/Cannoneer.png
wget https://beta.legiontd2.com/images/textures/Icons/HybridT1.png
wget https://beta.legiontd2.com/images/textures/Icons/HybridT2.png
wget https://beta.legiontd2.com/images/textures/Icons/HybridT3.png
wget https://beta.legiontd2.com/images/textures/Icons/HybridT4.png
wget https://beta.legiontd2.com/images/textures/Icons/HybridT5.png
wget https://beta.legiontd2.com/images/textures/Icons/HybridT6.png
wget https://beta.legiontd2.com/images/textures/Icons/MaskedSpirit.png
wget https://beta.legiontd2.com/images/textures/Icons/HellRaiser.png
wget https://beta.legiontd2.com/images/textures/Icons/FalseMaiden.png
wget https://beta.legiontd2.com/images/textures/Icons/Nekomata.png
wget https://beta.legiontd2.com/images/textures/Icons/Infiltrator.png
wget https://beta.legiontd2.com/images/textures/Icons/Town%28Prophet%29.png
wget https://beta.legiontd2.com/images/textures/Icons/Orchid.png
wget https://beta.legiontd2.com/images/textures/Icons/Blob.png
wget https://beta.legiontd2.com/images/textures/Icons/EternalWanderer.png
wget https://beta.legiontd2.com/images/textures/Icons/SamuraiSoul.png
wget https://beta.legiontd2.com/images/textures/Icons/Yozora.png
wget https://beta.legiontd2.com/images/textures/Icons/Arctaire.png
wget https://beta.legiontd2.com/images/textures/Icons/UpgradeSupply.png
wget https://beta.legiontd2.com/images/textures/Icons/Undeploy.png
wget https://beta.legiontd2.com/images/textures/Icons/Recall.png
git checkout button\ active.png
cd -
